"""add category to questions

Revision ID: 3a26c4f6833c
Revises: 76ecf28dae30
Create Date: 2026-07-03 10:19:02.963516

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a26c4f6833c"
down_revision: Union[str, Sequence[str], None] = "76ecf28dae30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Frozen snapshot of the default question -> category mapping as of this
# migration. Deliberately not imported from app.core.default_questions,
# since that module may change later and migrations must stay historically
# accurate regardless of future app code changes.
_DEFAULT_QUESTIONS_BY_CATEGORY = {
    "EARLY_LIFE_FAMILY": [
        "What is your full name, and is there a story behind why you were given it?",
        "When and where were you born?",
        "What do you know about your parents' and grandparents' lives?",
        "What language(s) did you grow up speaking at home?",
        "What is your earliest childhood memory?",
    ],
    "CHILDHOOD_FAMILY_LIFE": [
        "What was your childhood home like?",
        "Who were the most important people in your childhood, and why?",
        "What games or activities did you enjoy most as a child?",
        "Did you have any pets growing up? Tell me about them.",
        "What family traditions do you remember most fondly?",
        "What's the funniest thing that happened to you as a child?",
        "Was there a moment in your childhood that changed how you saw the world?",
    ],
    "SCHOOL_GROWING_UP": [
        "What was school like for you?",
        "Did you have a favourite teacher or subject? Why?",
        "What did you want to be when you grew up?",
        "Who was your best friend growing up, and what did you get up to together?",
        "What's a mistake you made when you were young that taught you something "
        "important?",
    ],
    "CAREER_WORK": [
        "How did you choose the path you took in life or work?",
        "What was your first job, and what did you learn from it?",
        "What achievement in your working life are you proudest of?",
        "Was there a moment your career took an unexpected turn?",
        "If you could go back, would you choose a different path?",
    ],
    "LOVE_RELATIONSHIPS": [
        "How did you meet your partner (or the great loves of your life)?",
        "What do you remember about your wedding day, or a moment of deep commitment?",
        "What's the secret to a relationship that lasts?",
        "What has being a parent (or aunt/uncle/mentor) taught you?",
        "Who has had the biggest influence on the person you became?",
    ],
    "MAJOR_LIFE_EVENTS": [
        "What has been the happiest moment of your life so far?",
        "What has been the hardest thing you've ever been through, and how did "
        "you get through it?",
        "Have you ever had to start over? What was that like?",
        "What's a risk you took that you're glad you took?",
        "Is there a place you've lived or visited that changed you?",
    ],
    "VALUES_BELIEFS_REFLECTIONS": [
        "What values do you try hardest to live by?",
        "What does happiness mean to you?",
        "What do you believe makes a life well lived?",
        "Has your faith or outlook on life changed over the years?",
        "What are you most grateful for?",
    ],
    "ADVICE_LEGACY": [
        "What's the best advice anyone ever gave you?",
        "What advice would you give to someone just starting out in life?",
        "What do you hope people remember about you?",
        "What do you want your children, grandchildren, or the people who love "
        "you to know?",
        "If you could tell your younger self one thing, what would it be?",
    ],
}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills any pre-existing rows to ADVICE_LEGACY (an
    # arbitrary but harmless fallback) since NOT NULL columns can't be added
    # to a non-empty table without one. The known default-seeded rows are
    # then corrected below to their real category via a one-time data fix;
    # only hypothetical pre-existing custom questions keep the fallback.
    op.add_column(
        "questions",
        sa.Column(
            "category",
            sa.Enum(
                "EARLY_LIFE_FAMILY",
                "CHILDHOOD_FAMILY_LIFE",
                "SCHOOL_GROWING_UP",
                "CAREER_WORK",
                "LOVE_RELATIONSHIPS",
                "MAJOR_LIFE_EVENTS",
                "VALUES_BELIEFS_REFLECTIONS",
                "ADVICE_LEGACY",
                name="questioncategory",
            ),
            nullable=False,
            server_default="ADVICE_LEGACY",
        ),
    )
    # ### end Alembic commands ###

    questions = sa.table(
        "questions",
        sa.column("text", sa.String),
        sa.column("category", sa.String),
    )
    for category, texts in _DEFAULT_QUESTIONS_BY_CATEGORY.items():
        for text in texts:
            op.execute(
                questions.update()
                .where(questions.c.text == text)
                .values(category=category)
            )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("questions") as batch_op:
        batch_op.drop_column("category")
    # ### end Alembic commands ###
