"""add user_type to users and add invites table

Revision ID: 8660f57cbe43
Revises: fd030632f803
Create Date: 2026-07-03 09:11:24.377344

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8660f57cbe43"
down_revision: Union[str, Sequence[str], None] = "fd030632f803"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column(
            "invited_user_type",
            sa.Enum("STORYTELLER", "STORY_REQUESTER", "VIEWER", name="usertype"),
            nullable=False,
        ),
        sa.Column("invited_by_user_id", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_invites_account_id"), "invites", ["account_id"], unique=False
    )
    op.create_index(op.f("ix_invites_email"), "invites", ["email"], unique=False)
    op.create_index(
        op.f("ix_invites_token_hash"), "invites", ["token_hash"], unique=True
    )
    # server_default backfills any pre-existing rows to story_requester (the
    # closest existing semantic match to "signed up and owns this account
    # themselves") since NOT NULL columns can't be added to a non-empty
    # table without one. New rows always set user_type explicitly going
    # forward, so the default is a one-time backfill aid, not a real default.
    op.add_column(
        "users",
        sa.Column(
            "user_type",
            sa.Enum("STORYTELLER", "STORY_REQUESTER", "VIEWER", name="usertype"),
            nullable=False,
            server_default="STORY_REQUESTER",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invites_token_hash"), table_name="invites")
    op.drop_index(op.f("ix_invites_email"), table_name="invites")
    op.drop_index(op.f("ix_invites_account_id"), table_name="invites")
    op.drop_table("invites")
    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_column("user_type")
    # ### end Alembic commands ###
