"""add answer_type and media fields to answers

Revision ID: 8e73b217cdea
Revises: ea1160dba301
Create Date: 2026-07-03 14:39:20.337434

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e73b217cdea"
down_revision: Union[str, Sequence[str], None] = "ea1160dba301"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows to TEXT — exact, not a guess,
    # since every Answer row prior to this migration was a text answer.
    op.add_column(
        "answers",
        sa.Column(
            "answer_type",
            sa.Enum("TEXT", "AUDIO", "VIDEO", name="answertype"),
            nullable=False,
            server_default="TEXT",
        ),
    )
    op.add_column("answers", sa.Column("media_path", sa.String(), nullable=True))
    op.add_column(
        "answers", sa.Column("media_content_type", sa.String(), nullable=True)
    )
    with op.batch_alter_table("answers") as batch_op:
        batch_op.alter_column("text", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("answers") as batch_op:
        batch_op.alter_column("text", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.drop_column("media_content_type")
        batch_op.drop_column("media_path")
        batch_op.drop_column("answer_type")
    # ### end Alembic commands ###
